import type {Metadata} from 'next'
import './globals.css'
import Link from "@mui/material/Link";
/* import Logo from "@/app/components/logo"; //전체 페이지에 서경대 로고 추가*/

export const metadata: Metadata = {
    title: '서경대 전화번호부 백오피스', // 브라우저 타이틀
    description: 'Generated by Beauty',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html>
        <body>
        <h1><Link href="/"><img src="/logo_christmas_desktop.png" alt=""/></Link></h1>{/*전체 페이지 공통*/}
        {children}
        </body>
        </html>
    )
}
